config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :frienddbs
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'frienddbs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frienddb.rb
class Frienddb < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :frienddbs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/frienddbs_controller.rb
class FrienddbsController < ApplicationController
  before_action :set_frienddb, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /frienddbs or /frienddbs.json
  def index
    @frienddbs = Frienddb.all
  end

  # GET /frienddbs/1 or /frienddbs/1.json
  def show
  end

  # GET /frienddbs/new
  def new
    #@frienddb = Frienddb.new
    @frienddb = current_user.frienddbs.build
  end

  # GET /frienddbs/1/edit
  def edit
  end

  # POST /frienddbs or /frienddbs.json
  def create
    #@frienddb = Frienddb.new(frienddb_params)
    @frienddb = current_user.frienddbs.build(frienddb_params)

    respond_to do |format|
      if @frienddb.save
        format.html { redirect_to @frienddb, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @frienddb }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @frienddb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frienddbs/1 or /frienddbs/1.json
  def update
    respond_to do |format|
      if @frienddb.update(frienddb_params)
        format.html { redirect_to @frienddb, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @frienddb }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @frienddb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frienddbs/1 or /frienddbs/1.json
  def destroy
    @frienddb.destroy
    respond_to do |format|
      format.html { redirect_to frienddbs_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @frienddb = current_user.frienddbs.find_by(id: params[:id])
    redirect_to frienddbs_path, notice: "Not Authorizes To Edit This Friend" if @frienddb.nil?

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frienddb
      @frienddb = Frienddb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def frienddb_params
      params.require(:frienddb).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    #local variable
    @about_me = "My Name is Thin Yanant Zaw..."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frienddbs_helper.rb
module FrienddbsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/frienddbs/_form.html.erb
<%= form_with(model: frienddb) do |form| %>
  <% if frienddb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(frienddb.errors.count, "error") %> prohibited this frienddb from being saved:</h2>

      <ul>
        <% frienddb.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name"  %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :email, class:"form-control", placeholder:"Email"  %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone"  %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter"  %>
  </div>
  <div class="field mb-3">
    <%= form.number_field :user_id, id: :frienddbs_user_id ,class:"form-control", value:current_user.id, type: :hidden  %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/frienddbs/edit.html.erb
<h1>Editing Friend</h1>
<br>
<%= render 'form', frienddb: @frienddb, class:"btn btn-secondary"  %>
<br>
<%= link_to 'Show', @frienddb, class:"btn btn-secondary" %> 

<%= link_to 'Delete', @frienddb, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>

<%= link_to 'Back', frienddbs_path, class:"btn btn-dark" %>

app/views/frienddbs/index.html.erb
<% if user_signed_in? %>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @frienddbs.each do |frienddb| %>
      <% if frienddb.user == current_user %>
      <tr>
        <td>
          <%= link_to frienddb.first_name+' '+frienddb.last_name, frienddb, class:"btn btn-link" %>
          
        </td>
        <td><%= frienddb.email %></td>
        <td><%= frienddb.phone %></td>
        <td><%= frienddb.twitter %></td>
        
        
        
        <td><%= link_to 'Delete', frienddb, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_frienddb_path, class:"btn btn-primary" %>
<% else %>
  <h1>Hello World</h1>
  This is my first Rails Webpage!
<% end %>

app/views/frienddbs/new.html.erb
<h1>Add New Friend</h1>
<br/>
<%= render 'form', frienddb: @frienddb, class:"btn btn-secondary" %>
<br/>
<%= link_to 'Back', frienddbs_path, class:"btn btn-dark" %>

app/views/frienddbs/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @frienddb.first_name %>
    <%= @frienddb.last_name %>
  </h1>
  <p class="lead">
    <%= @frienddb.email %>  |
    <%= @frienddb.phone %>  |
    <%= @frienddb.twitter %>
      
    </p>
    <br>
   <%= link_to 'Edit', edit_frienddb_path(@frienddb), class:"btn btn-secondary" %> 
   <%= link_to 'Delete', @frienddb, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
   <%= link_to 'Back', frienddbs_path, class:"btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Friends App', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
        
       

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Friends", new_frienddb_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Out",  destroy_user_session_path, method: :delete,  class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile",  edit_user_registration_path, class:"nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
   
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us ... </h1>
<p> <%= @about_me %> </p>
<p> 
	<% answer = 2 + 3 %> 
	2 + 3 = <%= answer %>
</p>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first Rails Webpage!

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    
    <style type="text/css">
    .jumbotron {
      padding: 4rem 2rem;
      margin-bottom: 2rem;
      background-color: var(--bs-light);
      border-radius: .3rem;  
    }
</style>

    <title>Friend App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>


    <div class="container">
      <br>

      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>